AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-screenshot-website

  Take a screenshot of a website using puppeteer and chromium
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 25

Resources:
  ScreenshotWebsiteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: screenshot/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 1024
      Layers:
        - arn:aws:lambda:us-east-1:527510119384:layer:chromium:1
        - arn:aws:lambda:us-east-1:527510119384:layer:zod:1
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  ScreenshotWebsiteFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      Cors:
        AllowMethods:
          - POST
        AllowOrigins:
          - '*'
      TargetFunctionArn: !Ref ScreenshotWebsiteFunction
Outputs:
  ScreenshotWebsiteFunction:
    Description: "Screenshot Website Lambda Function ARN"
    Value: !GetAtt ScreenshotWebsiteFunction.Arn
  ScreenshotWebsiteFunctionIamRole:
    Description: "Implicit IAM Role created for Screenshot Website function"
    Value: !GetAtt ScreenshotWebsiteFunctionRole.Arn
